## Assignment II: Slicing, Arrays, Functions, and Rotations 

**Total: 100 points.** Questions 1 to 3 (75 points: Q1 is 20 points, Q2 and Q3 are 25 points each, including the 5-point Submission), plus Question 4 (25 bonus points).

This assignment pulls together everything from Sep 9 to Sep 18: list and NumPy array slicing, array arithmetic, writing your own functions, generating lists, and building rotation matrices. **All arrays and lists in this assignment are 1D or 2D only.** You will not need (and should not use) any 3D or higher-dimensional arrays anywhere below.

- Each of Questions 1 to 3 is split into **Part (a)** and **Part (b)**.
- **Question 4 is an entirely bonus question worth 25 points.** It asks you to explore the relationship between SU(2) and SO(3), the famous "double cover," using only the tools you already have (complex numbers, 2D arrays, and functions).
- Write your code in the cell provided for each part, and make sure it **prints** your final answer(s) clearly, ideally with an f-string that says what the printed value represents.
- **Submission (5 points):** see the instructions at the very end of this notebook.


# Assignment II: Slicing, Arrays, Functions, and Rotations
**Name:** Wan Zikri Hakim Nizam  
**GitHub Repository:** https://github.com/hakimwsu/wsu_math300.git

**AI Usage Disclosure (student to fill in):**

## Hakim Nizam Assignment 2

**(Highlighted)** 

**AI tools (e.g., ChatGPT / GitHub Copilot) were used to assist in writing and structuring the helper functions as well as the primary main logic executed at the beginning of each question solution.**


### AI Usage Policy

**No AI tools (ChatGPT, Claude, GitHub Copilot's suggestion/chat features, etc.) may be used to generate, complete, or rewrite your solutions for this assignment.** All code and explanations must be your own work.

**Exception and disclosure requirement:** If you have **GitHub Copilot active** in your editor (e.g. inline autocomplete suggestions appearing as you type), you do not need to disable it, but you **must disclose this** by adding a short **markdown cell right below this one** stating:
- That Copilot (or any other AI tool) was active while you worked, and
- Briefly, how you used or did not use its suggestions (e.g. "Copilot was active but I did not accept any of its suggestions for graded cells" or "I accepted a Copilot suggestion for the boilerplate `for` loop in Q3(a) but wrote the logic myself").

Notebooks with AI-generated solutions that are not disclosed as above will not receive credit, regardless of correctness.


### Question 1: Slicing, Lists and NumPy Arrays (20 points)

**(a) [12 pts] Lists.** Create a list of at least 8 numbers called `my_list`. Using slicing (no loops), print:
1. The first 4 elements.
2. The last 4 elements.
3. Every 3rd element, starting from the first.
4. The list reversed.

**(b) [8 pts] 2D arrays.** Create a 5x5 NumPy array `M` containing the integers 1 through 25 (using `np.arange` and `.reshape`). Using slicing, print:
1. The 3rd row of `M`.
2. The 2nd column of `M`.
3. The 2x2 sub-matrix in the *bottom-right* corner of `M`.
4. `M` with its rows reversed, using slicing, **not** `np.flip`.


In [1]:
import numpy as np 

In [10]:
# TODO: your code for Q1(a) here

my_list = [12, 25, 37, 48, 51, 63, 74, 89, 90, 102]

print("--- Q1(a): Lists ---")
print(f"1. First 4 elements: {my_list[:4]}")
print(f"2. Last 4 elements: {my_list[-4:]}")
print(f"3. Every 3rd element from first: {my_list[::3]}")
print(f"4. List reversed: {my_list[::-1]}")

--- Q1(a): Lists ---
1. First 4 elements: [12, 25, 37, 48]
2. Last 4 elements: [74, 89, 90, 102]
3. Every 3rd element from first: [12, 48, 74, 102]
4. List reversed: [102, 90, 89, 74, 63, 51, 48, 37, 25, 12]


In [18]:
# TODO: your code for Q1(b) here

M = np.arange(1, 26).reshape(5, 5)

print("\n--- Q1(b): 2D NumPy Arrays ---")
print(f"Full Array M:\n{M}\n")
print(f"1. 3rd row of M: {M[2, :]}")
print(f"2. 2nd column of M: {M[:, 1]}")
print(f"3. 2x2 sub-matrix (bottom-right):\n{M[-2:, -2:]}")
print(f"4. M with rows reversed:\n{M[::-1, :]}")


--- Q1(b): 2D NumPy Arrays ---
Full Array M:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

1. 3rd row of M: [11 12 13 14 15]
2. 2nd column of M: [ 2  7 12 17 22]
3. 2x2 sub-matrix (bottom-right):
[[19 20]
 [24 25]]
4. M with rows reversed:
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


### Question 2: Arithmetic with NumPy Arrays (25 points)

**(a) [15 pts] Elementwise arithmetic with floats.** Create `x = np.linspace(1, 10, 10)` (this always gives you floats). Print `x + 3`, `x - 2`, `x * 4`, `x / 5`, `x ** 3`, and `np.sqrt(x)`. Then compute `y = np.sqrt(x) ** 2` and use `np.isclose(x, y)` to confirm that `y` matches `x` element by element, even though squaring a square root does not give back the *exact* original floating-point value.

*Example of how `np.isclose` works:* `np.isclose(0.0000001, 0)` returns `True`, because the two values are equal up to a small numerical tolerance, even though `0.0000001 == 0` would return `False`. This is exactly why we use `np.isclose` instead of `==` when comparing floating-point results, such as your `x` and `y` above: after the square root and the squaring, the values will differ from the originals by something like `1e-15`, not exactly `0.0`.

**(b) [10 pts] Matrix multiplication and standardization.** Create two `3x3` matrices `A` and `B` of your choice (any numbers). Compute their matrix product `A @ B` (**not** elementwise multiplication) and print it. Then confirm, using `np.allclose(A @ B, B @ A)`, that matrix multiplication is generally **not commutative** (this should print `False`, unless you happened to pick special matrices). Finally, compute a "standardized" version of `A`: subtract `A.mean()` and divide by `A.std()`. Print the standardized array, and confirm its new mean is (approximately) `0` using `np.isclose`.


In [25]:
# TODO: your code for Q2(a) here

x = np.linspace(1, 10, 10)

print("--- Q2(a): Elementwise Operations ---")
print(f"x + 3 = {x + 3}")
print(f"x - 2 = {x - 2}")
print(f"x * 4 = {x * 4}")
print(f"x / 5 = {x / 5}")
print(f"x ** 3 = {x ** 3}")
print(f"np.sqrt(x) = {np.sqrt(x)}")


--- Q2(a): Elementwise Operations ---
x + 3 = [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
x - 2 = [-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.]
x * 4 = [ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]
x / 5 = [0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
x ** 3 = [   1.    8.   27.   64.  125.  216.  343.  512.  729. 1000.]
np.sqrt(x) = [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [31]:
y = np.sqrt(x) ** 2
matches_elementwise = np.isclose(x, y)
print(f"\nDoes y match x elementwise? {matches_elementwise}")
print(f"All elements match within tolerance: {np.all(matches_elementwise)}")


Does y match x elementwise? [ True  True  True  True  True  True  True  True  True  True]
All elements match within tolerance: True


In [37]:
# TODO: your code for Q2(b) here

A = np.array([[2, 5, 8], [3, 1, 7], [4, 9, 6]])
B = np.array([[1, 0, 4], [2, 3, 5], [9, 1, 2]])

AB = A @ B
BA = B @ A

print("\n--- Q2(b): Matrix Multiplication & Standardization ---")
print(f"A @ B =\n{AB}")
is_commutative = np.allclose(AB, BA)
print(f"Is matrix multiplication commutative (A @ B == B @ A)? {is_commutative}")

A_std = (A - A.mean()) / A.std()
print(f"\nStandardized Array A:\n{A_std}")
mean_is_zero = np.isclose(A_std.mean(), 0)
print(f"Is standardized mean close to 0? {mean_is_zero} (Actual mean: {A_std.mean():.2e})")



--- Q2(b): Matrix Multiplication & Standardization ---
A @ B =
[[84 23 49]
 [68 10 31]
 [76 33 73]]
Is matrix multiplication commutative (A @ B == B @ A)? False

Standardized Array A:
[[-1.161895    0.          1.161895  ]
 [-0.77459667 -1.54919334  0.77459667]
 [-0.38729833  1.54919334  0.38729833]]
Is standardized mean close to 0? True (Actual mean: 0.00e+00)


### Question 3: Defining Functions and Generating Lists (25 points)

**Background: the double factorial.** For a positive integer $n$, the **double factorial** $n!!$ is the product of every second integer counting down from $n$ to either $1$ or $2$ (whichever has the same parity as $n$). For example:
- $6!! = 6 \times 4 \times 2 = 48$
- $7!! = 7 \times 5 \times 3 \times 1 = 105$

By convention, $0!! = 1$ and $1!! = 1$.

**(a) [15 pts] A simple generator function.** Write a function `double_factorial(n)` that computes and returns $n!!$ for a single non-negative integer `n`, using a `for` (or `while`) loop. Then write a function `double_factorials_up_to(n)` that uses a loop over `k = 1, ..., n` (calling your `double_factorial` function each time) to build and return a list of $[1!!, 2!!, 3!!, ..., n!!]$. Call it with `n = 10` and print the result.

**(b) [10 pts] A function with a custom recurrence.** Write a function `custom_sequence(a0, a1, n)` that returns a list of the first `n` terms of the sequence defined by $s_0 = a_0$, $s_1 = a_1$, and $s_k = 2 s_{k-1} + s_{k-2}$ for $k \geq 2$ (a "Pell-like" sequence). Give `a1` a default value of `1`. Call your function with `a0 = 0`, using the default for `a1`, for `n = 10` terms, and print the result.


In [42]:
# TODO: your code for Q3(a) here

def double_factorial(n):
    """Computes n!! for a non-negative integer n."""
    if n == 0 or n == 1:
        return 1
    result = 1
    for k in range(n, 0, -2):
        result *= k
    return result

def double_factorials_up_to(n):
    """Returns a list of [1!!, 2!!, ..., n!!]."""
    return [double_factorial(k) for k in range(1, n + 1)]

print("--- Q3(a): Double Factorials ---")
df_list = double_factorials_up_to(10)
print(f"Double factorials up to 10!!: {df_list}")


--- Q3(a): Double Factorials ---
Double factorials up to 10!!: [1, 2, 3, 8, 15, 48, 105, 384, 945, 3840]


In [46]:
# TODO: your code for Q3(b) here

def custom_sequence(a0, a1=1, n=10):
    """Returns the first n terms of s_k = 2*s_{k-1} + s_{k-2}."""
    if n <= 0:
        return []
    if n == 1:
        return [a0]
    
    seq = [a0, a1]
    for k in range(2, n):
        next_term = 2 * seq[k - 1] + seq[k - 2]
        seq.append(next_term)
    return seq

print("\n--- Q3(b): Custom Recurrence Sequence ---")
pell_seq = custom_sequence(a0=0, a1=1, n=10)
print(f"First 10 terms of sequence (a0=0, a1=1): {pell_seq}")



--- Q3(b): Custom Recurrence Sequence ---
First 10 terms of sequence (a0=0, a1=1): [0, 1, 2, 5, 12, 29, 70, 169, 408, 985]


### Question 4 (Bonus, 25 points): SU(2) and the Double Cover of SO(3)

You've already built rotation matrices $R_x, R_y, R_z \in SO(3)$: real $3\times 3$ matrices that rotate vectors in ordinary 3D space. There is a second way to describe the *same* rotations, using $2\times 2$ **complex** matrices instead. This is the group $SU(2)$.

**Reminder: $R_z(\theta)$.** For reference, here again is the rotation-about-$z$ matrix you built in Activity X:

$$
R_z(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

```python
def Rz(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])
```

**Background (given, no derivation needed).** A rotation by angle $\theta$ about a unit-vector axis $n = [n_x, n_y, n_z]$ (given to you as a plain Python **list** of three numbers), viewed as an element of $SU(2)$, is given by:

$$
U(\theta, n) =
\begin{bmatrix}
\cos\left(\dfrac{\theta}{2}\right) - i\,n_z \sin\left(\dfrac{\theta}{2}\right) & -(n_y + i\,n_x)\sin\left(\dfrac{\theta}{2}\right) \\[6pt]
(n_y - i\,n_x)\sin\left(\dfrac{\theta}{2}\right) & \cos\left(\dfrac{\theta}{2}\right) + i\,n_z \sin\left(\dfrac{\theta}{2}\right)
\end{bmatrix}
$$

You are also given the three Pauli matrices. In math notation, they are:

$$
\sigma_x = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \qquad
\sigma_y = \begin{bmatrix} 0 & -i \\ i & 0 \end{bmatrix}, \qquad
\sigma_z = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}
$$

and as NumPy arrays:

```python
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
paulis = [sigma_x, sigma_y, sigma_z]
```

Every $U \in SU(2)$ maps to an actual $3\times 3$ rotation matrix $R(U) \in SO(3)$ via the formula:

$$
R(U)_{jk} = \frac{1}{2}\,\mathrm{tr}\big(\sigma_j\, U\, \sigma_k\, U^\dagger\big), \qquad j, k \in \{x, y, z\}
$$

where $U^\dagger$ is the conjugate transpose of $U$ (`U.conj().T` in NumPy). Recall that the **trace** of a square matrix, written $\mathrm{tr}(\cdot)$, is just the sum of its diagonal entries; in NumPy you can compute it directly with `np.trace(A)` for any square array `A`, so you don't need to write a loop just to get the trace itself.

**(a) [15 pts]** Write a function `U(theta, n)` that takes an angle `theta` and an axis `n = [nx, ny, nz]` (a Python list), and returns the $2\times 2$ complex NumPy array given by the formula above. Write a function `su2_to_so3(M)` that builds the $3\times 3$ real matrix $R(M)$ using the second formula above (a double `for` loop over the `paulis` list is fine, using `np.trace` for the trace itself; take `.real` at the end, since the result should be real up to tiny numerical error). Using `n = [0, 0, 1]` (the $z$-axis) and an angle `theta` of your choice, confirm with `np.allclose` that `su2_to_so3(U(theta, n))` matches `Rz(theta)` (defined above).

**(b) [10 pts]** Here is a simpler way to see the double cover, using `Rz` and rotating **twice**. Here, $I$ denotes the identity matrix (in NumPy, `np.eye(n)` gives you the $n \times n$ identity). Let `n = [0, 0, 1]` and `theta = np.pi` (a half turn). Compute `U_half = U(theta, n)`, then "rotate twice" by composing this matrix with itself: `U_full = U_half @ U_half` (two half turns, applied one after another, make a full turn).
1. Use `np.allclose` to show that `U_full` equals `-np.eye(2)` (the *negative* identity), not the identity `np.eye(2)`, even though two half turns should bring you all the way back around.
2. Use `su2_to_so3` to show that `su2_to_so3(U_full)` matches `Rz(2 * np.pi)`, which should simply be the identity `3x3` matrix, since a full $2\pi$ rotation in ordinary 3D space does nothing at all.
3. Print a one or two sentence explanation of what this shows: two composed half turns return $SU(2)$ to $-I$ rather than back to $I$, yet the very same two half turns return $SO(3)$ to the identity, exactly as expected. Since two different $SU(2)$ matrices, $I$ and $-I$, both correspond to the very same $SO(3)$ rotation (doing nothing), $SU(2)$ is called a **double cover** of $SO(3)$.


**Note: how $R_{jk}$ connects to $R_z(\theta)$.** The nine numbers $R_{jk}$ for $j,k \in \{x,y,z\}$ are just the nine entries of the $3\times3$ matrix, with $j$ giving the row and $k$ giving the column. So checking that `su2_to_so3(U(theta, n))` equals `Rz(theta)` just means all nine of these entries should match. When `n = [0, 0, 1]`, the formula for `U(theta, n)` becomes a diagonal matrix, so `U` commutes with `sigma_z`, giving `R_zz = 1` and `R_xz = R_yz = R_zx = R_zy = 0`. For the remaining entries, using `sigma_x` and `sigma_y` conjugated by `U` and the identity `tr(sigma_j sigma_k) = 2` if `j = k`, else `0`, gives `R_xx = R_yy = cos(theta)`, `R_yx = sin(theta)`, and `R_xy = -sin(theta)`. Arranging these nine values into the $3\times3$ grid reproduces exactly `Rz(theta)`. This is why the loop over `paulis` in `su2_to_so3` should reconstruct `Rz(theta)` when tested with `n = [0, 0, 1]`.


In [50]:
def Rz(theta):
    """Standard 3D rotation matrix about the z-axis."""
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])

# Pauli matrices
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
paulis = [sigma_x, sigma_y, sigma_z]

In [53]:
# TODO: your code for Q4(a) here

def U(theta, n):
    """Returns 2x2 SU(2) matrix for rotation by angle theta about axis n=[nx, ny, nz]."""
    nx, ny, nz = n
    half_th = theta / 2.0
    cos_h = np.cos(half_th)
    sin_h = np.sin(half_th)
    
    u11 = cos_h - 1j * nz * sin_h
    u12 = -(ny + 1j * nx) * sin_h
    u21 = (ny - 1j * nx) * sin_h
    u22 = cos_h + 1j * nz * sin_h
    
    return np.array([[u11, u12], [u21, u22]], dtype=complex)

def su2_to_so3(M):
    """Maps a 2x2 SU(2) matrix M to a 3x3 SO(3) rotation matrix R."""
    R = np.zeros((3, 3))
    M_dag = M.conj().T
    for j in range(3):
        for k in range(3):
            val = 0.5 * np.trace(paulis[j] @ M @ paulis[k] @ M_dag)
            R[j, k] = val.real
    return R

print("--- Q4(a): SU(2) to SO(3) Mapping ---")
test_angle = np.pi / 4
z_axis = [0, 0, 1]

U_z = U(test_angle, z_axis)
R_mapped = su2_to_so3(U_z)
R_direct = Rz(test_angle)

print(f"Mapped R(U) Matrix:\n{R_mapped}")
print(f"Matches direct Rz(theta)? {np.allclose(R_mapped, R_direct)}")


--- Q4(a): SU(2) to SO(3) Mapping ---
Mapped R(U) Matrix:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Matches direct Rz(theta)? True


In [55]:
# TODO: your code for Q4(b) here

print("\n--- Q4(b): Double Cover Verification ---")
theta_half = np.pi
U_half = U(theta_half, z_axis)
U_full = U_half @ U_half

# 1. Compare U_full to -I
is_neg_I = np.allclose(U_full, -np.eye(2))
print(f"1. Is U_full equal to -I (2x2)? {is_neg_I}")

# 2. Compare mapped matrix to Rz(2*pi)
R_full_mapped = su2_to_so3(U_full)
R_2pi = Rz(2 * np.pi)
is_SO3_identity = np.allclose(R_full_mapped, R_2pi)
print(f"2. Does su2_to_so3(U_full) match Rz(2*pi)? {is_SO3_identity}")

# 3. Explanation
explanation = (
    "A full 2π rotation in SU(2) evaluates to -I rather than the identity matrix I. "
    "However, both I and -I in SU(2) map to the exact same 3x3 identity rotation matrix in SO(3). "
    "Because every 3D rotation in SO(3) corresponds to two distinct matrices (+U and -U) in SU(2), "
    "SU(2) acts as a double cover of SO(3)."
)
print(f"\n3. Explanation:\n{explanation}")



--- Q4(b): Double Cover Verification ---
1. Is U_full equal to -I (2x2)? True
2. Does su2_to_so3(U_full) match Rz(2*pi)? True

3. Explanation:
A full 2π rotation in SU(2) evaluates to -I rather than the identity matrix I. However, both I and -I in SU(2) map to the exact same 3x3 identity rotation matrix in SO(3). Because every 3D rotation in SO(3) corresponds to two distinct matrices (+U and -U) in SU(2), SU(2) acts as a double cover of SO(3).


### Submission Instructions (5 points)

Submit this assignment in two parts:

1. **CrowdMark:** Submit your completed notebook (or a PDF/printout of it, per your instructor's usual CrowdMark process) through CrowdMark as normal.
2. **GitHub (worth 5 points):** Push this completed notebook to a GitHub repository for Assignment II, and include the link to your GitHub repository as part of your CrowdMark submission (e.g. in a text box or as a comment on the first page).
   - **Either** make the repository **public**, so the link alone is enough, **or**
   - keep it **private** and add the instructor as a collaborator using the GitHub username `say-yas`.
3. Double check that the link you submit actually opens your repository (and that the notebook with your completed answers is visible in it) before submitting.

The 5 points here are awarded specifically for completing this GitHub step correctly (a working public link, or collaborator access granted on a private repo), and are counted toward the 100 point total alongside the base points from Questions 1 to 3 and the bonus points from Question 4.
